
import java.util.ArrayList;

public class ProblemManagement {
    private static ArrayList<Problem> problems = new ArrayList<Problem>();
    private static Problem problem;
    private static int question = 0, lineNumber;
    
  //@formatter:off
    // Sets everything. Call this or everything will throw errors
    public static void init() {
	problem = new Problem("During an isometric process, 450 joules of heat are* removed from a trapped gas. Which statement is true?", "The volume of the gas. is increasing", "The volume of the gas. is decreasing", "The temperature of the gas. is increasing", "The temperature of the gas. is decreasing", "Word = 450 J", "The temperature of the gas. is decreasing", "In an isometric process, volume is constant and work is zero. Therefore, internal energy decreases and temperature decreases.");
	problems.add(problem);
	problem = new Problem("A heat engine operates between 25ºC and 100ºC. The theoretical efficiency is most nearly: ", "10%", "20%", "50%", "70%", "80%", "20%", "e = (373 K - 298 K)/(373 K) = 0.2 = 20%");
	problems.add(problem);
	problem = new Problem("Three charges from left to right, A, B, and C, exist in a region of space. Charge A attracts B and B repels C. If A is positive, what is the sign of charge C?", "Positive", "Negative", "Left", "Right", "Neutral", "Negative", "A is positive and attracts B so B is negative. B repels C so C is also negative.");
	problems.add(problem);
	problem = new Problem("A 120-gram sample of iodine-131 has a half-life of 8.0 days. How much of the original sample remains after 24 days?", "120 g", "60 g", "30 g ", "15 g", "7.5 g", "15 g", "");
	problems.add(problem);
	problem = new Problem("Who came up with the plum pudding model of an atom?", "Max Planck", "Ernest Rutherford", "Albert Einstein", "Niels Bohr", "JJ Thomson", "JJ Thomson", "");
	problems.add(problem);
	problem = new Problem("During a thermodynamic process, 200 joules of heat are added to a gas* while 300 joules of work are done by the gas. Determine the change in internal energy.", "500 J", "100 J", "-100 J", "-500 J", "0 J", "-100 J", "ΔU = Q + W = 200 J - 300 J = -100 J");
	problems.add(problem);
	problem = new Problem("Two charges (q_1 and q_2) are separated by a distance r. What happens to force F if the charge on q_1 is doubled?", "0.25 F", "0.5 F", "1 F", "2 F", "4 F", "2 F", "F=(kq_1q_2)/d^2");
	problems.add(problem);
	problem = new Problem("What unit are charges measured in?", "Coulomb", "Volt", "Ampere", "Newton", "Watt", "Coulomb", "");
	problems.add(problem);
	problem = new Problem("What unit are electric potentials measured in?", "Coulomb", "Volt", "Ampere", "Teslas", "Watt", "Volt", "");
	problems.add(problem);
	problem = new Problem("What unit is current measured in?", "Farad", "Volt", "Ampere", "Ohm", "Watt", "Ampere", "");
	problems.add(problem);
	problem = new Problem("What unit is resistance measured in?", "Coulomb", "Volt", "Ampere", "Ohm", "Watt", "Ohm", "");
	problems.add(problem);
	problem = new Problem("What unit is power measured in?", "Coulomb", "Volt", "Ampere", "Teslas", "Watt", "Watt", "");
	problems.add(problem);
	problem = new Problem("What unit is capacitance measured in?", "Coulomb", "Farad", "Ampere", "Ohm", "Watt", "Farad", "");
	problems.add(problem);
	problem = new Problem("Three charges from left to right, A, B, and C, exist in a region of space. Charge A attracts B and B repels C. If A is positive, what is the sign of charge C?", "Positive", "Negative", "Left", "Right", "Neutral", "Negative", "A is positive and attracts B so B is negative. B repels C so C is also negative.");
	problems.add(problem);
	problem = new Problem("Three charges from left to right, A, B, and C, exist in a region of space. Charge A attracts B and B repels C. If A is negative, what is the sign of charge C?", "Positive", "Negative", "Left", "Right", "Neutral", "Positive", "A is negative and attracts B so B is positive. B repels C so C is also positive.");
	problems.add(problem);
	problem = new Problem("Two charged particles are identical other than their charge. One is (-∞,0) C and the other is (0,∞) C. What interaction do they undergo?", "Attraction", "Repulsion", "Explosion", "Nothing", "Magnetism", "Attraction", "Opposite charges attract.");
	problems.add(problem);
	problem = new Problem("Two charged particles are identical other than their charge. One is (-∞,0) C and the other is (-∞,0) C. What interaction do they undergo?", "Attraction", "Repulsion", "Explosion", "Nothing", "Magnetism", "Repulsion", "Same-sign charges repulse.");
	problems.add(problem);
	problem = new Problem("Two charged particles are identical other than their charge. One is (0,∞) C and the other is (0,∞) C. What interaction do they undergo?", "Attraction", "Repulsion", "Explosion", "Nothing", "Magnetism", "Repulsion", "Same-sign charges repulse.");
	problems.add(problem);
	problem = new Problem("Two charges (q_1 and q_2) are separated by a distance r. What happens to force F if the charge on q_1 is doubled?", "0.25 F", "0.5 F", "1 F", "2 F", "4 F", "2 F", "F=(kq_1q_2)/d^2");
	problems.add(problem);
	problem = new Problem("Two charges (q_1 and q_2) are separated by a distance r. What happens to force F if the charge on q_2 is halved?", "0.25 F", "0.5 F", "1 F", "2 F", "4 F", "0.5 F", "F=(kq_1q_2)/d^2");
	problems.add(problem);
	problem = new Problem("Two charges (q_1 and q_2) are separated by a distance r. What happens to force F if the distance is doubled?", "0.25 F", "0.5 F", "1 F", "2 F", "4 F", "0.25 F", "F=(kq_1q_2)/d^2");
	problems.add(problem);
	problem = new Problem("Two charges (q_1 and q_2) are separated by a distance r. What happens to force F if a charge and the distance are halved?", "0.25 F", "0.5 F", "1 F", "2 F", "4 F", "2 F", "F=(kq_1q_2)/d^2");
	problems.add(problem);
	problem = new Problem("What unit is magnetic field measured in?", "Tesla", "Newtons", "Tesla*Meters/Ampere", "Tesla*Meters Square", "Volts", "Tesla", "");
	problems.add(problem);
	problem = new Problem("What unit is the force of magnetism measured in?", "Tesla", "Newtons", "Tesla*Meters/Ampere", "Tesla*Meters Square", "Volts", "Newtons", "");
	problems.add(problem);
	problem = new Problem("What unit is permeability of free space measured in?", "Tesla", "Newtons", "Tesla*Meters/Ampere", "Tesla*Meters Square", "Volts", "Tesla*Meters/Ampere", "");
	problems.add(problem);
	problem = new Problem("What unit is magnetic flux measured in?", "Tesla", "Newtons", "Tesla*Meters/Ampere", "Tesla*Meters Square", "Volts", "Tesla*Meters Square", "");
	problems.add(problem);
	problem = new Problem("What unit is emf measured in?", "Tesla", "Newtons", "Tesla*Meters/Ampere", "Tesla*Meters Square", "Volts", "Volts", "");
	problems.add(problem);
	problem = new Problem("What are domains?", "Territory of an animal", "Groups of atoms with different. magnetic orientation", "Groups of atoms with similar. magnetic orientation", "Areas with magnetic fields", "Regions with electric fields", "Groups of atoms with similar. magnetic orientation", "");
	problems.add(problem);
	problem = new Problem("When finding the direction of magnetic fields using the. right-hand rule, what indicates field direction?", "The direction of the thumb", "The direction of the palm", "The direction of the curled fingers", "The direction of the current", "Out of the paper", "The direction of the curled fingers", "For right hand rule, point thumb in the direction of the current. The direction of the curled fingers indicates field direction.");
	problems.add(problem);
	problem = new Problem("What is the constant μ_0?", "The coefficient of friction", "The coefficient of electricity", "The coefficient of magnetism", "The permeability of free space", "The magnetic flux", "The permeability of free space", "");
	problems.add(problem);
	problem = new Problem("What is the formula for the magnitude of the magnetic field, B,* of a long, straight current-carrying wire?", "B = (μ_0I)/(2πr)", "B = μ_0I", "B = I/(2πr)", "B = μ_0/(2πr)", "B = Ir", "B = (μ_0I)/(2πr)", "");
	problems.add(problem);
	problem = new Problem("What is the equation for the force of magnetism on a. moving charge in a uniform magnetic field?", "FB = qvB", "FB = qB", "FB = μ_0qI", "FB = 2πrB", "FB = μ_0qB", "FB = qvB", "");
	problems.add(problem);
	problem = new Problem("What is the resulting motion of a magnetic field?", "Circular motion perpendicular. to the field", "Linear acceleration parallel. to the field", "Linear acceleration in the direction. of the field", "Simple harmonic motion", "No motion", "Circular motion perpendicular. to the field", "");
	problems.add(problem);
	problem = new Problem("When finding the direction of the force of magnetism* using the right-hand rule, what indicates the direction of the force?", "The direction of the thumb", "The direction of the fingers", "The direction the palm faces", "The direction of the back of the hand", "None of the above", "The direction the palm faces", "");
	problems.add(problem);
	problem = new Problem("A charge, q, moving at at a speed of v enters a uniform magnetic field, B. Determine the radius of the circular path.", "r = (mv^2)/(qB)", "r = (mv)/(qB)", "r = (mv^2)", "r = (mv^2)/q", "r = (mv^2)/B", "r = (mv2)/(qB)", "");
	problems.add(problem);
	problem = new Problem("What is the equation for the magnetic force on a* wire in an external magnetic field?", "FB = qvB", "FB = qIB", "FB = ILB", "FB = qIL", "FB = μ_0qI", "FB = ILB", "");
	problems.add(problem);
	problem = new Problem("Which of the following does not increase the amount* of voltage induced in a coil of wire?", "Move the magnet faster", "Move a stronger magnet", "Use more wire", "Move multiple magnets", "Move both magnets and wire. at the same speed", "Move both magnets and wire. at the same speed", "");
	problems.add(problem);
	problem = new Problem("What is magnetic flux?", "When an electric potential is induced", "When the current reaches a maximum", "When the force of magnetism. reaches a maximum", "A change in the magnetic field", "All of the above", "A change in the magnetic field", "");
	problems.add(problem);
	problem = new Problem("What is an emf?", "When an electric potential is induced", "When the current reaches a maximum", "When the force of magnetism. reaches a maximum", "A change in the magnetic field", "All of the above", "When an electric potential is induced", "");
	problems.add(problem);
	problem = new Problem("What is the equation for magnetic flux?", "Φ = BA", "Φ = BI", "Φ = Bmv^2", "Φ = Bq", "Φ = AI", "Φ = BA", "");
	problems.add(problem);
	problem = new Problem("What is the equation for an emf?", "ϵ = (ΔΦ)/t", "ϵ = ΔΦ", "ϵ = (ΔΦ)/(2πr)", "ϵ = ΔΦB", "ϵ = BLv", "ϵ = (ΔΦ)/t", "");
	problems.add(problem);
	problem = new Problem("What is the equation of a motional emf?", "ϵ = (ΔΦ)/t", "ϵ = ΔΦ", "ϵ = (ΔΦ)/(2πr)", "ϵ = ΔΦB", "ϵ = BLv", "ϵ = BLv", "");
	problems.add(problem);
	problem = new Problem("What unit is wavelength measured in?", "Newtons", "Volts", "Meters", "Meters/Second", "None of the above", "Meters", "");
	problems.add(problem);
	problem = new Problem("What unit is the speed of light measured in?", "Newtons", "Volts", "Meters", "Meters/Second", "None of the above", "Meters/Second", "");
	problems.add(problem);
	problem = new Problem("In transverse waves, oscillators vibrate:", "Diagonal to the direction. of wave propagation", "Perpendicular to the direction. of wave propagation", "Parallel to the direction. of wave propagation", "To a minimum degree", "None of the above", "Perpendicular to the direction. of wave propagation", "");
	problems.add(problem);
	problem = new Problem("In longitudinal waves, oscillators vibrate:", "Diagonal to the direction. of wave propagation", "Perpendicular to the direction. of wave propagation", "Parallel to the direction. of wave propagation", "To a minimum degree", "None of the above", "Parallel to the direction. of wave propagation", "");
	problems.add(problem);
	problem = new Problem("What is the amplitude of a wave?", "The range of the graph", "The domain of the graph", "The distance between the. equilibrium line and any. point on the wave", "The distance measured between. two successive identical portions. of a wave", "None of the above", "The distance between the. equilibrium line and any. point on the wave", "");
	problems.add(problem);
	problem = new Problem("What is the wavelength of a wave?", "The range of the graph", "The domain of the graph", "The distance between the equilibrium. and any point on the wave", "The distance measured between two. successive identical portions. of a wave", "None of the above", "The distance measured between two. successive identical portions of a wave", "");
	problems.add(problem);
	problem = new Problem("What is the equation for the speed of a wave?", "v = Aλ", "v = λ/s", "v = (fλ)/s", "v = (Afλ)/s", "v = fλ", "v = fλ", "");
	problems.add(problem);
	problem = new Problem("If you see a wave traveling in only one medium, then the wave has:", "I) Constant wave speed", "II) Constant frequency", "III) Inverse relationship between. frequency and wavelength", "I and III", "II and III", "I and III", "");
	problems.add(problem);
	problem = new Problem("If you see a wave changing mediums, then the wave has:", "I) Constant wave speed", "II) Constant frequency", "III) Direct relationship between. velocity and wavelength", "I and III", "II and III", "II and III", "");
	problems.add(problem);
	problem = new Problem("A wave travels through a medium with* velocity v, frequency f, and wavelength λ. If the wave travels then enters another medium that increases the velocity* to 2v, what will be the corresponding frequency and wavelength?", "f, 2λ", "0.5f, λ", "f, λ", "0.5f, 4λ", "2f, λ", "f, 2λ", "");
	problems.add(problem);
	problem = new Problem("What is the equation for the speed of light moving in a vacuum?", "c = Aλ", "c = λ/s", "c = (fλ)/s", "c = (Afλ)/s", "c = fλ", "c = fλ", "");
	problems.add(problem);
	problem = new Problem("Which electromagnetic wave has the highest energy?", "Infrared", "Ultra-violet", "X-rays", "Gamma rays", "Radio waves", "Gamma rays", "");
	problems.add(problem);
	problem = new Problem("Which electromagnetic wave has the lowest energy?", "Infrared", "Ultra-violet", "X-rays", "Gamma rays", "Radio waves", "Radio waves", "");
	problems.add(problem);
	problem = new Problem("A sound wave has a frequency of f, a velocity of v, and a wavelength of λ. If the frequency were doubled, how would speed and wavelength be affected?", "v, λ", "2v, λ", "v, 2λ", "v/2 , λ", "v, λ/2", "v, λ/2", "");
	problems.add(problem);
	problem = new Problem("When light moving in air enters a block* of glass, which propert(ies) do NOT change?", "Wave speed", "Wavelength", "Frequency", "Both wavelength and frequency", "Both wave speed and wavelength", "Frequency", "");
	problems.add(problem);
	problem = new Problem("As an ambulance siren approaches an observer, the observer will perceive a:", "Frequency increase due to. a wave speed increase", "Frequency increase due to. a wave speed decrease", "Frequency increase due to. a wavelength increase", "Frequency increase due to. a wavelength decrease", "Frequency decrease due to. wavelength increase", "Frequency increase due to. a wavelength decrease", "");
	problems.add(problem);
	problem = new Problem("What characteristic of a wave is affected during the superposition of waves?", "Amplitude", "Frequency", "Pitch", "Wavelength", "Wave speed", "Amplitude", "");
	problems.add(problem);
	problem = new Problem("What is the node of a standing wave?", "(A) Where constructive. interference occurs", "(B) Where destructive. interference occurs", "(C) Where the amplitude is maximum", "(D) A and C", "(E) B and C", "(B) Where destructive. interference occurs", "");
	problems.add(problem);
	problem = new Problem("What are brightness of light and the volume of sound associated with?", "Amplitude", "Frequency", "Wavelength", "Wave speed", "Superposition", "Amplitude", "");
	problems.add(problem);
	problem = new Problem("What is the pitch of a musical instrument and the color of light associated with?", "Amplitude", "Frequency", "Wavelength", "Wave speed", "Superposition", "Frequency", "");
	problems.add(problem);
	problem = new Problem("What does the variable n represent?", "Critical angle", "Radius of curvature", "Focal distance", "Magnification", "Index of refraction", "Index of refraction", "");
	problems.add(problem);
	problem = new Problem("What does the variable θ_c represent?", "Critical angle", "Radius of curvature", "Focal distance", "Magnification", "Index of refraction", "Critical angle", "");
	problems.add(problem);
	problem = new Problem("What does the variable R represent?", "Critical angle", "Radius of curvature", "Focal distance", "Magnification", "Index of refraction", "Radius of curvature", "");
	problems.add(problem);
	problem = new Problem("What does the variable f represent?", "Critical angle", "Radius of curvature", "Focal distance", "Magnification", "Index of refraction", "Focal distance", "");
	problems.add(problem);
	problem = new Problem("What does the variable M represent?", "Critical angle", "Radius of curvature", "Focal distance", "Magnification", "Index of refraction", "Magnification", "");
	problems.add(problem);
	problem = new Problem("What is the law of reflection?", "180 - θ_i = θ_r ", "θ_i = 180 - θ_r", "θ_i = 2θ_r", "2θ_i = θ_r", "θ_i = θ_r", "θ_i = θ_r", "");
	problems.add(problem);
	problem = new Problem("What is the equation for the index of refraction?", "n = v/c", "n = c/v", "n = c^2/v^2", "n = cv", "n = c + v", "n = c/v", "");
	problems.add(problem);
	problem = new Problem("Which of the following is not a characteristic* of an image formed by a plane mirror?", "The image is upright", "The image is the same size. as the object", "The image is a virtual image", "Image distance and object. distance are equal", "The image is inverted", "The image is inverted", "");
	problems.add(problem);
	problem = new Problem("What is Snell’s Law?", "n_1cosθ_1 = n_2cosθ_2", "n_1sinθ_1 = n_2cosθ_2", "n_1sinθ_1 = n_2sinθ_2", "n_1cosθ_1 = n_2sinθ_2", "n_1 = n_2", "n_1sinθ_1 = n_2sinθ_2", "");
	problems.add(problem);
	problem = new Problem("When a light ray is shone from a dense medium into air and* the incident angle is slowly increased, total internal reflection is* first noticed when the incident angle reaches 53o. Determine the index of refraction of the initial dense medium in simplest terms.", "n_1 = 1/(sin53)", "n_1 = (n_2sinθ_2)/(sin53)", "n_1 = n_2/(sin53)", "n_1 = (sinθ_2)/(sin53)", "n_1 = sin53", "n_1 = 1/(sin53)", "");
	problems.add(problem);
	problem = new Problem("What is the equation for the magnification, M, of an image?", "M = (h_i)(h_0)", "M = h_0/h_i", "M = h_i + h_0", "M = h_i - h_0", "M = h_i/h_0", "M = h_i/h_0", "");
	problems.add(problem);
	problem = new Problem("In the case of a concave mirror, an object is initially located at 2f. How will the image change as the object moves toward the focal point f?", "The image will increase in size and. move away from the mirror", "The image will increase in size and. move toward the mirror", "The image will decrease in size and. move away from the mirror", "The image will decrease in size and. move toward the mirror", "The image size remains constant but. moves away from the mirror", "The image will increase in size and. move away from the mirror", "");
	problems.add(problem);
	problem = new Problem("What is a key geometric relationship between the focal length, f, of the lens,* the object distance, do, and the image distance, d_i?", "1/f = 1/d_o + 1/d_i", "f = d_o + d_i", "f = 1/d_o + 1/d_i", "4f = 2d_o + 2d_i", "1/f = 1/d_o - 1/d_i", "1/f = 1/d_o + 1/d_i", "");
	problems.add(problem);
	problem = new Problem("Which of the following is NOT true for a concave lens?", "Concave lens are divergent", "The image is virtual", "The image is upright", "The image is larger than the object", "The image forms on the near side. of the lens", "The image is larger than the object", "");
	problems.add(problem);
	problem = new Problem("Which of the following is true when light enters a denser medium?", "v increases, λ decreases,. and n increases", "v increases, λ decreases,. and n decreases", "v decreases, λ increases,. and n increases", "v decreases, λ decreases,. and n increases", "v decreases, λ decreases,. and n decreases", "v decreases, λ decreases,. and n increases", "");
	problems.add(problem);
	problem = new Problem("What does the variable m refer to in physical optics?", "A specific maximum or minimum", "Distance measured to. maximum or minimum", "Angle measured to. maximum or minimum", "Slit spacing", "Distance from slits to screen", "A specific maximum or minimum", "");
	problems.add(problem);
	problem = new Problem("What does the variable L refer to in physical optics?", "A specific maximum or minimum", "Distance measured to. maximum or minimum", "Angle measured to. maximum or minimum", "Slit spacing", "Distance from slits to screen", "Distance from slits to screen", "");
	problems.add(problem);
	problem = new Problem("What does the variable d refer to in physical optics?", "A specific maximum or minimum", "Distance measured to. maximum or minimum", "Angle measured to. maximum or minimum", "Slit spacing", "Distance from slits to screen", "Slit spacing", "");
	problems.add(problem);
	problem = new Problem("What does the variable x_m refer to in physical optics?", "A specific maximum or minimum", "Distance measured to. maximum or minimum", "Angle measured to. maximum or minimum", "Slit spacing", "Distance from slits to screen", "Distance measured to. maximum or minimum", "");
	problems.add(problem);
	problem = new Problem("What does the variable θ_m refer to in physical optics?", "A specific maximum or minimum", "Distance measured to. maximum or minimum", "Angle measured to. maximum or minimum", "Slit spacing", "Distance from slits to screen", "Angle measured to. maximum or minimum", "");
	problems.add(problem);
	problem = new Problem("In physical optics, what is the equation to calculate x_m?", "x_m = (mL)/d", "x_m = mλL", "x_m = (mλL)/d", "x_ m = mλLd", "x_m = m/d", "x_m = (mλL)/d", "");
	problems.add(problem);
	problem = new Problem("Light on two narrow slits is used to project an* interference pattern onto a screen. How will the interference pattern (xm) change if the distance between* the slits is doubled?", "(x_m)/2", "2x_m", "(x_m)/4", "x_m", "4x_m", "(x_m)/2", "");
	problems.add(problem);
	problem = new Problem("What does a polarizing filter do?", "(A) Disperses light into. different wavelengths", "(B) Only allows light with the correct. direction of vibration to. pass through", "(C) Absorbs certain wavelengths. of light", "(A) and (C)", "None of the above", "(B) Only allows light with the correct. direction of vibration to. pass through", "");
	problems.add(problem);
	problem = new Problem("An object is placed on the principal axis of a convex lens a distance* 9.72 times the length of the focal length. The image formed will be:", "Real, upright, enlarged", "Real, inverted, and smaller", "Virtual, upright, and enlarged", "Virtual, upright, and smaller", "No image", "Real, inverted, and smaller", "");
	problems.add(problem);
	problem = new Problem("An object is placed on the principal axis of a convex lens a distance* 2.54 times the length of the focal length. The image formed will be:", "Real, inverted, enlarged", "Real, inverted, and smaller", "Virtual, upright, and enlarged", "Virtual, upright, and same size", "No image", "Real, inverted, and smaller", "");
	problems.add(problem);
	problem = new Problem("An object is placed on the principal axis of a convex lens a distance* 2 times the length of the focal length. The image formed will be:", "Real, upright, enlarged", "Real, inverted, and same size", "Real, inverted, and smaller", "Virtual, upright, and enlarged", "No image", "Real, inverted, and same size", "");
	problems.add(problem);
	problem = new Problem("An object is placed on the principal axis of a convex lens a distance* 1.678 times the length of the focal length. The image formed will be:", "Real, upright, enlarged", "Real, inverted, enlarged", "Virtual, upright, and enlarged", "Virtual, upright, and smaller", "No image", "Real, inverted, enlarged", "");
	problems.add(problem);
	problem = new Problem("An object is placed on the principal axis of a convex lens the focal point. The image formed will be:", "Real, upright, enlarged", "Real, inverted, enlarged", "Real, inverted, and smaller", "Virtual, upright, and enlarged", "No image", "No image", "");
	problems.add(problem);
	problem = new Problem("An object is placed on the principal axis of a convex lens a distance* 0.118 times the length of the focal length. The image formed will be:", "Real, upright, enlarged", "Real, inverted, enlarged", "Real, inverted, and smaller", "Virtual, upright, and enlarged", "Virtual, upright, and smaller", "Virtual, upright, and enlarged", "");
	problems.add(problem);
	problem = new Problem("Which object placement creates no image?", "d = 2f", "d = 3f", "f < d < 2f", "d = f", "d < f", "d = f", "");
	problems.add(problem);
	problem = new Problem("Which object placement creates a virtual image?", "d = 2f", "d = 3f", "f < d < 2f", "d = f", "d < f", "d < f", "");
	problems.add(problem);
	problem = new Problem("Which object placement creates an image behind the* object if the mirror is in front?", "d = 2f", "d = 3f", "f < d < 2f", "d = f", "d < f", "d < f", "");
	problems.add(problem);
	problem = new Problem("How many laws of thermodynamics are there?", "1", "2", "3", "4", "5", "4", "");
	problems.add(problem);
	problem = new Problem("What does the first law of thermodynamics state?", "Conservation of energy", "Entropy increases naturally", "The speed of light is constant. in all inertial frames", "For every action there is an equal. and opposite reaction", "None of the above", "Conservation of energy", "");
	problems.add(problem);
	problem = new Problem("What does the second laws thermodynamics state?", "Conservation of energy", "Entropy increases naturally", "The speed of light is constant. in all inertial frames", "For every action there is an equal. and opposite reaction", "None of the above", "Entropy increases naturally", "");
	problems.add(problem);
	problem = new Problem("What is entropy?", "The surrounding environment", "Disorder", "The Doppler Effect", "Highest Tree Layer in a rainforest", "None of the above", "Disorder", "");
	problems.add(problem);
	problem = new Problem("In thermodynamics, what does the variable U represent?", "Electric potential energy", "Gravitational potential energy", "Heat", "The internal energy of the system", "The external energy of the system", "The internal energy of the system", "");
	problems.add(problem);
	problem = new Problem("In thermodynamics, what does the variable e represent?", "Energy", "Efficiency", "Electron", "Einstein", "None of the above", "Efficiency", "");
	problems.add(problem);
	problem = new Problem("What is the equation for the change in internal energy of a gas?", "ΔU = (1/2)nRΔT", "ΔU = nRΔT", "ΔU = (3/2)nRΔT", "ΔU = (3/2)ΔT", "ΔU = ΔT", "ΔU = (3/2)nRΔT", "");
	problems.add(problem);
	problem = new Problem("During a thermodynamic process, 200 joules of heat are added to a gas* while 300 joules of work are done by the gas. Determine the change in internal energy.", "500 J", "100 J", "-100 J", "-500 J", "0 J", "-100 J", "ΔU = Q + W = 200 J - 300 J = -100 J");
	problems.add(problem);
	problem = new Problem("During an isothermal process, 1,000 joules of heat* are removed from a trapped gas. Determine the change in internal energy of the gas.", "ΔU = -1,000 J", "ΔU = 0 J", "ΔU = 1,000 J", "ΔU = -500 J", "ΔU = 500 J", "ΔU = 0 J", "In an isothermal process, the temperature remains constant so the internal energy does not change.");
	problems.add(problem);
	problem = new Problem("During an isothermal process, 1,000 joules of heat* are added from a trapped gas. Determine the work done on or by the gas.", "W = 1,000 J", "W = 0 J", "W = -1,000 J", "W = -500 J", "W = 500 J", "W = -1,000 J", "ΔU = Q + W -> 0 = (1000 J) + W -> W = -1,000 J");
	problems.add(problem);
	problem = new Problem("In thermodynamics, what is the equation for efficiency?", "e = (T_C - T_H)/T_H", "e = (T_H - T_C)/T_C", "e = (T_C - T_H)/T_C", "e = (T_H - T_C)/T_H", "e = (TH - TC)", "e = (T_H - T_C)/T_H", "");
	problems.add(problem);
	problem = new Problem("In an isothermal process:", "The temperature is zero", "The volume change is zero", "The work is zero", "The heat added is zero", "The internal energy change is zero", "The internal energy change is zero", "");
	problems.add(problem);
	problem = new Problem("In an adiabatic process, there is no:", "Change in pressure", "Change in volume", "Change in temperature", "Change in internal energy", "Heat added or removed", "Heat added or removed", "");
	problems.add(problem);
	problem = new Problem("During a thermodynamic process, 500 joules of heat are removed from a gas* while 300 joules of work are done on the gas. Determine the change in internal energy.", "-800 J", "-200 J", "0 J", "200 J", "800 J", "-200 J", "-500 + 300 = -200 J");
	problems.add(problem);
	problem = new Problem("A heat engine operates between 25ºC and 100ºC. The theoretical efficiency is most nearly: ", "10%", "20%", "50%", "70%", "80%", "20%", "e = (373 K - 298 K)/(373 K) = 0.2 = 20%");
	problems.add(problem);
	problem = new Problem("During an isometric process, 450 joules of heat are* removed from a trapped gas. Which statement is true?", "The volume of the gas. is increasing", "The volume of the gas. is decreasing", "The temperature of the gas. is increasing", "The temperature of the gas. is decreasing", "Word = 450 J", "The temperature of the gas. is decreasing", "In an isometric process, volume is constant and work is zero. Therefore, internal energy decreases and temperature decreases.");
	problems.add(problem);
	problem = new Problem("What does the variable α represent?", "Thermal conductivity ", "Specific heat capacity", "Universal gas constant", "Heat", "Coefficient of linear expansion", "Coefficient of linear expansion", "");
	problems.add(problem);
	problem = new Problem("What does the variable R represent?", "Thermal conductivity ", "Specific heat capacity", "Universal gas constant", "Heat", "Coefficient of linear expansion", "Universal gas constant", "");
	problems.add(problem);
	problem = new Problem("What does the variable Q represent?", "Thermal conductivity ", "Specific heat capacity", "Universal gas constant", "Heat", "Coefficient of linear expansion", "Heat", "");
	problems.add(problem);
	problem = new Problem("What does the variable k represent?", "Thermal conductivity", "Specific heat capacity", "Universal gas constant", "Heat", "Coefficient of linear expansion", "Thermal conductivity", "");
	problems.add(problem);
	problem = new Problem("What does the variable c represent?", "Thermal conductivity ", "Specific heat capacity", "Universal gas constant", "Heat", "Coefficient of linear expansion", "Specific heat capacity", "");
	problems.add(problem);
	problem = new Problem("The idea gas law relates all of the following but:", "Pressure", "Volume", "Temperature", "Time", "All of the above", "Time", "");
	problems.add(problem);
	problem = new Problem("What is the equation for the ideal gas law?", "PV = nRT", "P/V = n/(RT)", "PV = nT", "PV = RT", "P = nRTV", "PV = nRT", "");
	problems.add(problem);
	problem = new Problem("What is Boyle’s Law?", "All objects have gaseous forms", "All objects expand when heated", "PV=nRT", "(P_1)(V_1)=(P_2)(V_2)", "PV = T/V", "(P_1)(V_1)=(P_2)(V_2)", "");
	problems.add(problem);
	problem = new Problem("What is Charles’ Law?", "Temperature remains constant. during phase change", "All objects expand when heated", "PV=nRT", "(V_1)/(T_1)=(V_2)/(T_2)", "PV = T/V", "(V_1)/(T_1)=(V_2)/(T_2)", "");
	problems.add(problem);
	problem = new Problem("Under isothermal conditions, what would be the volume of a 1 L* sample of helium gas after its pressure changed from 12 atm to 4 atm?", "0 L", "3 L", "8 L", "16 L", "48 L", "3 L", "");
	problems.add(problem);
	problem = new Problem("If the temperature of 2 liters of gas is isobarically* changed from 10º C to 293º C, what would be the final volume?", "1.2 L", "2 L", "10 L", "293 L", "None of the above", "None of the above", "Use Charles’ Law");
	problems.add(problem);
	problem = new Problem("Which of the following is NOT true of an ideal gas?", "No intermolecular forces.", "Random motion.", "No volume.", "Elastic collisions.", "All are true.", "All are true.", "");
	problems.add(problem);
	problem = new Problem("A sample of nitrogen occupies 50 liters at standard temperature. Assuming constant pressure, what volume will* nitrogen occupy if the temperature is doubled?", "25 liters", "50 liters", "100 liters", "200 liters", "2500 liters", "100 liters", "");
	problems.add(problem);
	problem = new Problem("What is the final pressure of a gas that expands from 1 L* at 10º C to 10 L at 100º C if the original pressure was 3 atm?", "0.3 atm", "0.4 atm", "3 atm", "4 atm", "30 atm", "0.4 atm", "");
	problems.add(problem);
	problem = new Problem("Who came up with the plum pudding model of an atom?", "Max Planck", "Ernest Rutherford", "Albert Einstein", "Niels Bohr", "JJ Thomson", "JJ Thomson", "");
	problems.add(problem);
	problem = new Problem("Who discovered that the atom is mostly empty space* with a tiny region containing all the positive charge?", "Max Planck", "Ernest Rutherford", "Albert Einstein", "Niels Bohr", "JJ Thomson", "Ernest Rutherford", "");
	problems.add(problem);
	problem = new Problem("Who discovered that electrons occupy exact energy levels?", "Max Planck", "Ernest Rutherford", "Albert Einstein", "Niels Bohr", "JJ Thomson", "Niels Bohr", "");
	problems.add(problem);
	problem = new Problem("Who developed an equation that relates the energy* of a photon of light to its wavelength?", "Max Planck", "Ernest Rutherford", "Albert Einstein", "Niels Bohr", "JJ Thomson", "Albert Einstein", "");
	problems.add(problem);
	problem = new Problem("Who developed a mathematical relationship for atomic oscillations?", "Max Planck", "Ernest Rutherford", "Albert Einstein", "Niels Bohr", "JJ Thomson", "Max Planck", "");
	problems.add(problem);
	problem = new Problem("What is the equation that relates the energy of* a photo of light to its wavelength?", "E = hcλ", "E = (hc)/λ", "E = λ/(hc)", "E = hc", "E = hλ", "E = (hc)/λ", "");
	problems.add(problem);
	problem = new Problem("How are the frequency and wavelength affected when* the energy of photons is doubled?", "Frequency is halved,. wavelength is doubled", "Frequency is doubled,. wavelength is halved", "Frequency is halved,. wavelength is halved", "Frequency is doubled,. wavelength is doubled", "Frequency is doubled,. wavelength is 0", "Frequency is doubled,. wavelength is halved", "The frequency of light is directly proportional to energy. The wavelength of light isinversely proportional to energy.");
	problems.add(problem);
	problem = new Problem("What is an alpha particle?", "Photons that lack atomic. numbers and mass numbers", "An electron produced when. a neutron undergoes a transmutation. to become a proton", "A product of radioactive decay. and nuclear reactions", "The nucleus of a helium atom. without any electrons", "None of the above", "The nucleus of a helium atom. without any electrons", "");
	problems.add(problem);
	problem = new Problem("What is a beta particle?", "Photons that lack atomic. numbers and mass numbers", "An electron produced when. a neutron undergoes a transmutation. to become a proton", "A product of radioactive decay. and nuclear reactions", "The nucleus of a helium atom. without any electrons", "None of the above", "An electron produced when. a neutron. undergoes a transmutation. to become a proton", "");
	problems.add(problem);
	problem = new Problem("What is a neutrino?", "Photons that lack atomic. numbers and mass numbers", "An electron produced when. a neutron undergoes a transmutation. to become a proton", "A product of radioactive decay. and nuclear reactions", "The nucleus of a helium atom. without any electrons", "None of the above", "A product of radioactive decay. and nuclear reactions", "");
	problems.add(problem);
	problem = new Problem("What is a gamma ray?", "Photons that lack atomic. numbers and mass numbers", "An electron produced when. a neutron undergoes a transmutation. to become a proton", "A product of radioactive decay. and nuclear reactions", "The nucleus of a helium atom. without any electrons", "None of the above", "Photons that lack atomic. numbers and mass numbers", "");
	problems.add(problem);
	problem = new Problem("A 120-gram sample of iodine-131 has a half-life of 8.0 days. How much of the original sample remains after 24 days?", "120 g", "60 g", "30 g ", "15 g", "7.5 g", "15 g", "");
	problems.add(problem);
	problem = new Problem("What is fission?", "Combining smaller atoms. to make a larger atom", "The splitting of a large. atom into smaller atoms", "Radioactive decay", "All of the above", "None of the above", "The splitting of a large. atom into smaller atoms", "");
	problems.add(problem);
	problem = new Problem("What is fusion?", "Combining smaller atoms. to make a larger atom", "The splitting of a large. atom into smaller atoms", "Radioactive decay", "All of the above", "None of the above", "Combining smaller atoms. to make a larger atom", "");
	problems.add(problem);
    }
  //@formatter:on
    
    public static Problem getProblem() {
	if (question < 7) { // Sets first 7 questions always (in order).
	    question++;
	    int questionNumber = question - 1;
	    lineNumber = 12 + (2 * questionNumber);
	    return problems.get(questionNumber).randomize();
	} else {
	    int questionNumber = (int) (Math.random() * problems.size());
	    lineNumber = 12 + (2 * questionNumber);
	    return problems.get(questionNumber).randomize();
	}
    }
    
    public static int getLineNumber() {
	return lineNumber;
    }
}
